INSERT INTO `medicacao` (`codigo`, `descricao`) VALUES
	(1, 'Acular - cetorolaco de trometamina - EMS'),
	(2, 'Acular - cetorolaco de trometamina - Nature''s Plus'),
	(3, 'Acular - cetorolaco de trometamina - Sigma Pharma'),
	(4, 'Adalat Retard - nifedipino - EMS'),
	(5, 'Adriblastina RD - cloridrato de doxorrubicina - Eurofarma '),
	(6, 'Adriblastina RD - cloridrato de doxorrubicina - Asta Medica'),
	(7, 'Aerolin - sulfato de salbutamol - Greenpharma'),
	(8, 'Aerolin - sulfato de salbutamol - União Química'),
	(9, 'Aerolin - sulfato de salbutamol - Teuto'),
	(10, 'Aerolin - sulfato de salbutamol - EMS'),
	(11, 'Aerolin - sulfato de salbutamol - Neo Química'),
	(12, 'Aerolin - sulfato de salbutamol - Prati, Donaduzzi'),
	(13, 'Aerolin - sulfato de salbutamol - Theodoro F Sobral'),
	(14, 'Aerolin - sulfato de salbutamol - Cristália'),
	(15, 'Aerolin - sulfato de salbutamol - Medley'),
	(16, 'Afrin - cloridrato de oximetazolina - Cinfa'),
	(17, 'Akineton - cloridrato de biperideno - Abbott '),
	(18, 'Aldactone - espironolactona - EMS'),
	(19, 'Aldactone - espironolactona - Nature''s Plus'),
	(20, 'Aldomet - metildopa - Ranbaxy'),
	(21, 'Aldomet - metildopa - EMS'),
	(22, 'Aldomet - metildopa - Luper'),
	(23, 'Aldomet - metildopa - Medley'),
	(24, 'Aldomet - metildopa - Biosintética'),
	(25, 'Allegra - cloridrato de fexofenadina - Brainfarma'),
	(26, 'Allegra - cloridrato de fexofenadina - Mepha'),
	(27, 'Allegra - cloridrato de fexofenadina - Ranbaxy'),
	(28, 'Alphagan - brimonidina - Alcon'),
	(29, 'Amaryl - glimepirida - Biosintética'),
	(30, 'Amaryl - glimepirida - Esterlina'),
	(31, 'Amaryl - glimepirida - Eurofarma'),
	(32, 'Aminofilina  - aminofilina  - Teuto'),
	(33, 'Aminofilina  - aminofilina  - EMS'),
	(34, 'Aminofilina  - aminofilina  - Teuto'),
	(35, 'Amoxil - amoxicilina - Eurofarma '),
	(36, 'Amoxil - amoxicilina - Medley '),
	(37, 'Amoxil - amoxicilina - Apotex'),
	(38, 'Amoxil - amoxicilina - EMS'),
	(39, 'Amoxil - amoxicilina - Abbott '),
	(40, 'Amoxil - amoxicilina - Mepha'),
	(41, 'Amoxil - amoxicilina - Nature''s Plus '),
	(42, 'Amoxil - amoxicilina - Neo Química'),
	(43, 'Amoxil - amoxicilina - Prati, Donaduzzi'),
	(44, 'Amoxil - amoxicilina - Ranbaxy'),
	(45, 'Amoxil - amoxicilina - União Química'),
	(46, 'Amoxil - amoxicilina - Abbott '),
	(47, 'Amoxil - amoxicilina - Apotex'),
	(48, 'Amoxil - amoxicilina - Brainfarma'),
	(49, 'Amoxil - amoxicilina - Cinfa'),
	(50, 'Amoxil - amoxicilina - EMS'),
	(51, 'Amoxil - amoxicilina - Eurofarma '),
	(52, 'Amoxil - amoxicilina - Luper'),
	(53, 'Amoxil - amoxicilina - Medley '),
	(54, 'Amoxil - amoxicilina - Mepha'),
	(55, 'Amoxil - amoxicilina - Nature´s Plus '),
	(56, 'Amoxil - amoxicilina - Neo Química'),
	(57, 'Amoxil - amoxicilina - Ranbaxy'),
	(58, 'Amoxil - amoxicilina - Teuto'),
	(59, 'Amoxil - amoxicilina - Sanval'),
	(60, 'Amoxil - amoxicilina - EMS'),
	(61, 'Amoxil - amoxicilina - Eurofarma'),
	(62, 'Amoxil BD - amoxicilina - EMS'),
	(63, 'Amoxil BD - amoxicilina - Eurofarma'),
	(64, 'Amoxil BD - amoxicilina - Nature''s Plus'),
	(65, 'Amoxil BD - amoxicilina - Sigma Pharma'),
	(66, 'Amplacilina - ampicilina - Luper'),
	(67, 'Amplacilina - ampicilina - Novartis'),
	(68, 'Amplacilina - ampicilina - Abbott'),
	(69, 'Amplacilina - ampicilina - Eurofarma'),
	(70, 'Amplacilina - ampicilina - EMS'),
	(71, 'Amplacilina - ampicilina - Eurofarma'),
	(72, 'Amplacilina - ampicilina - Neo Química'),
	(73, 'Amplacilina - ampicilina - EMS'),
	(74, 'Amplacilina - ampicilina sódica - Teuto'),
	(75, 'Amplacilina - ampicilina sódica - EMS'),
	(76, 'Amplacilina - ampicilina sódica - Prodotti'),
	(77, 'Amplacilina - ampicilina sódica - Ranbaxy'),
	(78, 'Anafranil - cloridrato de clomipramina - EMS'),
	(79, 'Anafranil - cloridrato de clomipramina - Nature ''s Plus'),
	(80, 'Anafranil - cloridrato de clomipramina - Sigma Pharma'),
	(81, 'Antak  - cloridrato de ranitidina - EMS'),
	(82, 'Antak  - cloridrato de ranitidina - AB Farmoquímica'),
	(83, 'Antak  - cloridrato de ranitidina - Apotex'),
	(84, 'Antak  - cloridrato de ranitidina - Ativus'),
	(85, 'Antak  - cloridrato de ranitidina - Cinfa'),
	(86, 'Antak  - cloridrato de ranitidina - Eurofarma'),
	(87, 'Antak  - cloridrato de ranitidina - Hexal'),
	(88, 'Antak  - cloridrato de ranitidina - Medley '),
	(89, 'Antak  - cloridrato de ranitidina - Merck'),
	(90, 'Antak  - cloridrato de ranitidina - Novartis'),
	(91, 'Antak  - cloridrato de ranitidina - Ranbaxy'),
	(92, 'Antak  - cloridrato de ranitidina - Teuto'),
	(93, 'Antak  - cloridrato de ranitidina - EMS'),
	(94, 'Antak  - cloridrato de ranitidina - Eurofarma'),
	(95, 'Antak  - cloridrato de ranitidina - Hypofarma'),
	(96, 'Antak  - cloridrato de ranitidina - Teuto'),
	(97, 'Antak  - cloridrato de ranitidina - União Química'),
	(98, 'Aredia - pamidronato dissódico - Eurofarma'),
	(99, 'Aropax - cloridrato de paroxetina - Apotex'),
	(100, 'Aropax - cloridrato de paroxetina - Brainfarma'),
	(101, 'Aropax - cloridrato de paroxetina - Eurofarma'),
	(102, 'Aropax - cloridrato de paroxetina - Mepha'),
	(103, 'Aropax - cloridrato de paroxetina - Ranbaxy'),
	(104, 'Aspirina - acido acetilsalicilico - EMS'),
	(105, 'Aspirina - acido acetilsalicilico - Greepharma'),
	(106, 'Atenol  - atenolol  - Hexal'),
	(107, 'Atenol  - atenolol  - Medley'),
	(108, 'Atenol  - atenolol  - Biosintética'),
	(109, 'Atenol  - atenolol  - Bristol'),
	(110, 'Atenol  - atenolol  - Cristália'),
	(111, 'Atenol  - atenolol  - EMS'),
	(112, 'Atenol  - atenolol  - Ipca'),
	(113, 'Atenol  - atenolol  - Medley'),
	(114, 'Atenol  - atenolol  - Nature''s Plus'),
	(115, 'Atenol  - atenolol  - Novartis'),
	(116, 'Atenol  - atenolol  - Ranbaxy'),
	(117, 'Atenol  - atenolol  - Abbott'),
	(118, 'Atenol  - atenolol  - Apotex'),
	(119, 'Atenol  - atenolol  - Arrow'),
	(120, 'Atenol  - atenolol  - Cinfa'),
	(121, 'Atenol  - atenolol  - Merck'),
	(122, 'Atenol  - atenolol  - Teuto'),
	(123, 'Atlansil - cloridrato de amiodarona - Biosintética'),
	(124, 'Atrovent - brometo de ipratropio - Prati, Donaduzzi'),
	(125, 'Atrovent - brometo de ipratropio - União Química'),
	(126, 'Aurorix - moclobemida - Hexal'),
	(127, 'Aurorix - moclobemida - Apotex'),
	(128, 'Azactam - aztreonam - Eurofarma'),
	(129, 'Bactrim e Bactrim F - sulfametoxazol + trimetoprima - Nature´s Plus '),
	(130, 'Bactrim e Bactrim F - sulfametoxazol + trimetoprima - Neo Química'),
	(131, 'Bactrim e Bactrim F - sulfametoxazol + trimetoprima - Teuto'),
	(132, 'Bactrim e Bactrim F - sulfametoxazol + trimetoprima - Teuto'),
	(133, 'Bactrim e Bactrim F - sulfametoxazol + trimetoprima - EMS'),
	(134, 'Bactrim e Bactrim F - sulfametoxazol + trimetoprima - Apotex'),
	(135, 'Bactroban - mupirocina - Cristália'),
	(136, 'Baycuten-N - clotrimazol + acetato de dexametasona - Medley'),
	(137, 'Baycuten-N - clotrimazol + acetato de dexametasona - Prati, Donaduzzi'),
	(138, 'Benzetacil - benzilpenicilina benzatina - Eurofarma '),
	(139, 'Berlison - acetato de hidrocortisona - Ativus'),
	(140, 'Berotec - bromidato de fenoterol - EMS'),
	(141, 'Betnovate - valerato de betametasona   - EMS'),
	(142, 'Betnovate - valerato de betametasona   - Eurofarma'),
	(143, 'Betnovate - valerato de betametasona   - Medley '),
	(144, 'Betnovate - valerato de betametasona   - Prati, Donaduzzi'),
	(145, 'Betnovate - valerato de betametasona   - EMS'),
	(146, 'Betnovate - valerato de betametasona   - Eurofarma'),
	(147, 'Betnovate - valerato de betametasona   - Medley '),
	(148, 'Betnovate - valerato de betametasona   - Nature''s Plus'),
	(149, 'Betnovate - valerato de betametasona   - Neo Química'),
	(150, 'Betnovate - valerato de betametasona   - Prati, Donaduzzi'),
	(151, 'Betnovate - valerato de betametasona   - EMS'),
	(152, 'Betnovate - valerato de betametasona   - Medley '),
	(153, 'Betnovate - valerato de betametasona   - EMS'),
	(154, 'Betnovate - valerato de betametasona   - Medley '),
	(155, 'Betnovate N - valerato de betametasoa + sulfato de neomicina - EMS'),
	(156, 'Betnovate N - valerato de betametasoa + sulfato de neomicina - Prati, Donaduzzi'),
	(157, 'Betoptic - cloridrato de betaxolol - Cristália'),
	(158, 'Betoptic - cloridrato de betaxolol - Alcon'),
	(159, 'Biamotil - cloridrato de ciprofloxacino - Ranbaxy'),
	(160, 'Biamotil - cloridrato de ciprofloxacino - Alcon'),
	(161, 'Binotal  - ampicilina - EMS'),
	(162, 'Biovir - zidovudina + lamivudina - Ranbaxy'),
	(163, 'Bisolvon - cloridrato de bromexina - Medley '),
	(164, 'Bisolvon - cloridrato de bromexina - Prati, Donaduzzi'),
	(165, 'Bricanyl - sulfato de terbutalina - Medley'),
	(166, 'Bricanyl - sulfato de terbutalina - Merck'),
	(167, 'Bricanyl - sulfato de terbutalina - Prati, Donaduzzi'),
	(168, 'Bricanyl Expectorante - sulfato de terbutalina + guaifenesina - Medley'),
	(169, 'Bricanyl Expectorante - sulfato de terbutalina + guaifenesina - Prati, Donaduzzi'),
	(170, 'Brismucol - acebrofilina - EMS'),
	(171, 'Brismucol - acebrofilina - Biosintética'),
	(172, 'Brismucol - acebrofilina - Eurofarma'),
	(173, 'Brismucol - acebrofilina - Medley'),
	(174, 'Brismucol - acebrofilina - Nature''s Plus'),
	(175, 'Brismucol - acebrofilina - Sigma Pharma'),
	(176, 'Bufedil - cloridrato de buflomedil - Hexal'),
	(177, 'Buscopan  - brometo de n-butilescopolamina - Teuto'),
	(178, 'Buscopan  - brometo de n-butilescopolamina - EMS'),
	(179, 'Buscopan  - brometo de n-butilescopolamina - Nature''s Plus'),
	(180, 'Buscopan  - brometo de n-butilescopolamina - Prati, Donaduzzi'),
	(181, 'Buscopan  - brometo de n-butilescopolamina - Sigma Pharma'),
	(182, 'Buscopan composto  - brometo de n-butilescopolamina + dipirona sódica  - EMS'),
	(183, 'Buscopan composto  - brometo de n-butilescopolamina + dipirona sódica  - EMS'),
	(184, 'Buscopan composto  - brometo de n-butilescopolamina + dipirona sódica  - Medley'),
	(185, 'Buscopan composto  - brometo de n-butilescopolamina + dipirona sódica  - Prati, Donaduzzi'),
	(186, 'Buspar - cloridrato de buspirona - Apotex'),
	(187, 'Camptosar - cloridrato de irinotecano - Eurofarma'),
	(188, 'Candicort - cetoconazol+ dipropionato de betametasona - Medley'),
	(189, 'Candicort - cetoconazol+ dipropionato de betametasona - EMS'),
	(190, 'Candicort - cetoconazol+ dipropionato de betametasona - Eurofarma'),
	(191, 'Candicort - cetoconazol+ dipropionato de betametasona - Medley'),
	(192, 'Candicort - cetoconazol+ dipropionato de betametasona - EMS'),
	(193, 'Candicort - cetoconazol+ dipropionato de betametasona - Eurofarma'),
	(194, 'Canesten  - clotrimazol - Greenpharma'),
	(195, 'Canesten  - clotrimazol - Neo Química'),
	(196, 'Canesten  - clotrimazol - EMS'),
	(197, 'Canesten  - clotrimazol - Medley '),
	(198, 'Canesten  - clotrimazol - Prati, Donaduzzi'),
	(199, 'Canesten  - clotrimazol - Ranbaxy'),
	(200, 'Canesten  - clotrimazol - Ranbaxy'),
	(201, 'Capoten - captopril - Nature''’s Plus'),
	(202, 'Capoten - captopril - Novartis '),
	(203, 'Capoten - captopril - Cinfa'),
	(204, 'Capoten - captopril - Apotex'),
	(205, 'Capoten - captopril - Biosintética'),
	(206, 'Capoten - captopril - Cristália'),
	(207, 'Capoten - captopril - EMS'),
	(208, 'Capoten - captopril - Eurofarma'),
	(209, 'Capoten - captopril - Hexal'),
	(210, 'Capoten - captopril - Luper'),
	(211, 'Capoten - captopril - Medley '),
	(212, 'Capoten - captopril - Merck'),
	(213, 'Capoten - captopril - Ranbaxy'),
	(214, 'Capoten - captopril - Sigma Pharma'),
	(215, 'Capoten - captopril - Vitapan'),
	(216, 'Cardizem - cloridrato de diltiazem - Biosintética'),
	(217, 'Cardizen SR - cloridrato de diltiazem - Apotex'),
	(218, 'Carduran - mesilato de doxazosina - Apotex'),
	(219, 'Carduran - mesilato de doxazosina - Merck'),
	(220, 'Carduran - mesilato de doxazosina - Hexal'),
	(221, 'Cataflam D - diclofenaco - Teuto'),
	(222, 'Cataflam - diclofenaco potássico - Abbott'),
	(223, 'Cataflam - diclofenaco potássico - EMS'),
	(224, 'Cataflam - diclofenaco potássico - Apotex'),
	(225, 'Cataflam - diclofenaco potássico - Biosintética'),
	(226, 'Cataflam - diclofenaco potássico - Brainfarma'),
	(227, 'Cataflam - diclofenaco potássico - EMS'),
	(228, 'Cataflam - diclofenaco potássico - Medley'),
	(229, 'Cataflam - diclofenaco potássico - Medley '),
	(230, 'Cataflam - diclofenaco potássico - Mepha'),
	(231, 'Cataflam - diclofenaco potássico - Novartis'),
	(232, 'Cataflam - diclofenaco potássico - Ranbaxy'),
	(233, 'Cataflam - diclofenaco potássico - Teuto'),
	(234, 'Cataflam - diclofenaco potássico - Teuto'),
	(235, 'Cataflam - diclofenaco resinato - Biosintética'),
	(236, 'Cataflam - diclofenaco resinato - EMS'),
	(237, 'Cataflam - diclofenaco resinato - Medley '),
	(238, 'Cataflam - diclofenaco resinato - Nature´s Plus'),
	(239, 'Cataflam - diclofenaco resinato - Sigma Pharma'),
	(240, 'Cataflam Emulgel - diclofenaco dietilamônio - Biosintética'),
	(241, 'Cataflam Emulgel - diclofenaco dietilamônio - Cristália'),
	(242, 'Cataflam Emulgel - diclofenaco dietilamônio - EMS'),
	(243, 'Cataflam Emulgel - diclofenaco dietilamônio - Eurofarma'),
	(244, 'Cataflam Emulgel - diclofenaco dietilamônio - Medley '),
	(245, 'Cataflam Emulgel - diclofenaco dietilamônio - Nature''s Plus'),
	(246, 'Cataflam Emulgel - diclofenaco dietilamônio - Neo Química'),
	(247, 'Cataflam Emulgel - diclofenaco dietilamônio - Ranbaxy'),
	(248, 'Cataflam Emulgel - diclofenaco dietilamônio - Sigma Pharma'),
	(249, 'Cataflam Emulgel - diclofenaco dietilamônio - Teuto'),
	(250, 'Cartrax - tioconazol + tinidazol - Ativus'),
	(251, 'Cartrax - tioconazol + tinidazol - EMS'),
	(252, 'Cartrax - tioconazol + tinidazol - Medley'),
	(253, 'Cartrax - tioconazol + tinidazol - Nature’s Plus'),
	(254, 'Cartrax - tioconazol + tinidazol - Prati, Donaduzzi'),
	(255, 'Ceclor - cefaclor - Novartis'),
	(256, 'Ceclor - cefaclor - Medley'),
	(257, 'Ceclor - cefaclor - Apotex'),
	(258, 'Ceclor - cefaclor - Ranbaxy'),
	(259, 'Ceclor - cefaclor - Mepha'),
	(260, 'Ceclor - cefaclor - EMS'),
	(261, 'Ceclor - cefaclor - EMS'),
	(262, 'Ceclor - cefaclor - Medley'),
	(263, 'Ceclor AF - cefaclor - Ranbaxy'),
	(264, 'Cedur - benzafibrato - EMS'),
	(265, 'Cedur - benzafibrato - Nature''s Plus'),
	(266, 'Cedur - benzafibrato - Sigma Pharma'),
	(267, 'Cefamox - cefadroxil - Abbott'),
	(268, 'Cefamox - cefadroxil - EMS'),
	(269, 'Cefamox - cefadroxil - Novartis'),
	(270, 'Cefamox - cefadroxil - Eurofarma'),
	(271, 'Cefamox - cefadroxil - Ranbaxy'),
	(272, 'Cefamox - cefadroxil - Abbott '),
	(273, 'Cefamox - cefadroxil - Apotex'),
	(274, 'Cefamox - cefadroxil - EMS'),
	(275, 'Cefamox - cefadroxil - Eurofarma '),
	(276, 'Cefamox - cefadroxil - Mepha'),
	(277, 'Cefamox - cefadroxil - Novartis'),
	(278, 'Cefamox - cefadroxil - Ranbaxy'),
	(279, 'Cefamox - cefadroxila - Medley'),
	(280, 'Cefamox - cefadroxila - '),
	(281, 'Cefamox - cefadroxila - '),
	(282, 'Cefamox - cefadroxila - Brainfarma'),
	(283, 'Celestamine - maleato de dexclorfeniramina + betametasona - Eurofarma'),
	(284, 'Celestamine - maleato de dexclorfeniramina + betametasona - Cristália'),
	(285, 'Celestamine - maleato de dexclorfeniramina + betametasona - EMS'),
	(286, 'Celestamine - maleato de dexclorfeniramina + betametasona - Medley'),
	(287, 'Celestamine - maleato de dexclorfeniramina + betametasona - Prati, Donaduzzi'),
	(288, 'Celestamine - maleato de dexclorfeniramina + betametasona - Teuto'),
	(289, 'Celestamine - maleato de dexclorfeniramina + betametasona - União Química'),
	(290, 'Celestone - betametasona - EMS'),
	(291, 'Celestone - betametasona - Eurofarma'),
	(292, 'Celestone - betametasona - Nature’s Plus'),
	(293, 'Celestone - betametasona - Prati, Donaduzzi'),
	(294, 'Celestone - betametasona - Sigma Pharma'),
	(295, 'Celestone - betametasona - EMS'),
	(296, 'Celestone - betametasona - Eurofarma'),
	(297, 'Celestone - betametasona - Medley'),
	(298, 'Celestone - betametasona - Prati, Donaduzzi'),
	(299, 'Celestone - betametasona - EMS'),
	(300, 'Celestone - betametasona - Eurofarma'),
	(301, 'Celestone - betametasona - Nature''s Plus'),
	(302, 'Celestone - betametasona - Sigma Pharma'),
	(303, 'Cellcept - micofenolato mofetil - Cellofarm'),
	(304, 'Cipramil - citalopram - Brainfarma'),
	(305, 'Cipramil - citalopram - Arrow'),
	(306, 'Cipramil - citalopram - Eurofarma'),
	(307, 'Cipramil - citalopram - Hexal'),
	(308, 'Cipramil - citalopram - Mepha'),
	(309, 'Cipramil - citalopram - Merck'),
	(310, 'Cipramil - citalopram - Ranbaxy'),
	(311, 'Cipro - ciprofloxacino - Eurofarma '),
	(312, 'Cipro - ciprofloxacino - Halex Istar'),
	(313, 'Cipro - ciprofloxacino - Ranbaxy'),
	(314, 'Cipro - cloridrato de ciprofloxacino - Ranbaxy'),
	(315, 'Cipro - cloridrato de ciprofloxacino - AB Farmoquímica'),
	(316, 'Cipro - cloridrato de ciprofloxacino - Arrow'),
	(317, 'Cipro - cloridrato de ciprofloxacino - Cinfa'),
	(318, 'Cipro - cloridrato de ciprofloxacino - Hexal'),
	(319, 'Cipro - cloridrato de ciprofloxacino - EMS'),
	(320, 'Cipro - cloridrato de ciprofloxacino - Mepha'),
	(321, 'Cipro - cloridrato de ciprofloxacino - Novartis'),
	(322, 'Cipro - cloridrato de ciprofloxacino - Ranbaxy'),
	(323, 'Cipro - cloridrato de ciprofloxacino - Neo Química'),
	(324, 'Cipro - cloridrato de ciprofloxacino - Zydus'),
	(325, 'Claforan  - cefotaxima sódica  - Ranbaxy'),
	(326, 'Claforan  - cefotaxima sódica  - AB Farmoquímica'),
	(327, 'Claritin - loratadina - Ativus'),
	(328, 'Claritin - loratadina - Brainfarma'),
	(329, 'Claritin - loratadina - EMS'),
	(330, 'Claritin - loratadina - Medley '),
	(331, 'Claritin - loratadina - Merck'),
	(332, 'Claritin - loratadina - Prati, Donaduzzi'),
	(333, 'Claritin - loratadina - União Química'),
	(334, 'Claritin - loratadina - Apotex'),
	(335, 'Claritin - loratadina - Brainfarma'),
	(336, 'Claritin - loratadina - Cinfa'),
	(337, 'Claritin - loratadina - Hexal'),
	(338, 'Claritin - loratadina - Mepha'),
	(339, 'Claritin - loratadina - Merck'),
	(340, 'Claritin - loratadina - Novartis'),
	(341, 'Claritin - loratadina - Ranbaxy'),
	(342, 'Claritin - loratadina - Biosintética'),
	(343, 'Claritin D - loratadina+sulfato de pseudoefedrina - Brainfarma'),
	(344, 'Claritin D - loratadina+sulfato de pseudoefedrina - EMS'),
	(345, 'Claritin D - loratadina+sulfato de pseudoefedrina - Brainfarma'),
	(346, 'Claritin D - loratadina+sulfato de pseudoefedrina - Eurofarma'),
	(347, 'Claritin D - loratadina+sulfato de pseudoefedrina - Medley'),
	(348, 'Claritin D - loratadina+sulfato de pseudoefedrina - Nature ''s Plus'),
	(349, 'Claritin D - loratadina+sulfato de pseudoefedrina - Novartis'),
	(350, 'Claritin D - loratadina+sulfato de pseudoefedrina - Sigma Pharma'),
	(351, 'Clavulin - amoxicilina+clavulanato de potássio - Ranbaxy'),
	(352, 'Clavulin - amoxicilina+clavulanato de potássio - Mepha'),
	(353, 'Clavulin - amoxicilina+clavulanato de potássio - EMS'),
	(354, 'Clavulin - amoxicilina+clavulanato de potássio - Brainfarma'),
	(355, 'Clavulin - amoxicilina+clavulanato de potássio - Brainfarma'),
	(356, 'Clavulin - amoxicilina+clavulanato de potássio - EMS'),
	(357, 'Clavulin - amoxicilina+clavulanato de potássio - Mepha'),
	(358, 'Clavulin - amoxicilina+clavulanato de potássio - Novartis'),
	(359, 'Clavulin - amoxicilina+clavulanato de potássio - Ranbaxy'),
	(360, 'Clavulin - amoxicilina+clavulanato de potássio - Merck'),
	(361, 'Clavulin BD - amoxicilina+clavulanato de potássio - Novartis'),
	(362, 'Clavulin BD - amoxicilina+clavulanato de potássio - Ranbaxy'),
	(363, 'Co-Renitec - maleato de enalapril + hidroclorotiazida - Biosintética'),
	(364, 'Co-Renitec - maleato de enalapril + hidroclorotiazida - Novartis'),
	(365, 'Co-Renitec - maleato de enalapril + hidroclorotiazida - Nature’s Plus'),
	(366, 'Co-Renitec - maleato de enalapril + hidroclorotiazida - EMS'),
	(367, 'Co-Renitec - maleato de enalapril + hidroclorotiazida - Medley'),
	(368, 'Co-Renitec - maleato de enalapril + hidroclorotiazida - Merck'),
	(369, 'Co-Renitec - maleato de enalapril + hidroclorotiazida - Nature ''s Plus'),
	(370, 'Co-Renitec - maleato de enalapril + hidroclorotiazida - Sigma Pharma'),
	(371, 'Concor - fumarato de bisoprolol - Hexal'),
	(372, 'Coreg - carvedilol - Biosintética'),
	(373, 'Cosopt - cloridrato de dorzolamida + maleato de timolol - Biosintética'),
	(374, 'Cozaar - losartan potássico - Mepha'),
	(375, 'Cozaar - losartan potássico - Ranbaxy'),
	(376, 'Cozaar - losartan potássico - Biosintética '),
	(377, 'Cozaar - losartan potássico - Brainfarma'),
	(378, 'Cozaar - losartan potássico - Eurofarma'),
	(379, 'Cozaar - losartan potássico - Medley'),
	(380, 'Cozaar - losartan potássico - Merck'),
	(381, 'Cozaar - losartan potássico - Novartis'),
	(382, 'Cozaar - losartana potássica - Cristália'),
	(383, 'Crixivan - sulfato de indinavir - Ranbaxy'),
	(384, 'Cromolerg - cromoglicato dissódico - Alcon'),
	(385, 'Cymevene - ganciclovir sódico - Eurofarma'),
	(386, 'Daktarin  - nitrato de miconazol - Cristalia'),
	(387, 'Daktarin  - nitrato de miconazol - EMS'),
	(388, 'Daktarin  - nitrato de miconazol - Medley'),
	(389, 'Daktarin  - nitrato de miconazol - Nature’s Plus'),
	(390, 'Daktarin  - nitrato de miconazol - Neo Química'),
	(391, 'Daktarin  - nitrato de miconazol - Prati, Donaduzzi'),
	(392, 'Daktarin  - nitrato de miconazol - Sigma Pharma'),
	(393, 'Daktarin  - nitrato de miconazol - Teuto'),
	(394, 'Daktarin  - nitrato de miconazol - EMS'),
	(395, 'Daktarin  - nitrato de miconazol - Nature’s Plus'),
	(396, 'Daktarin  - nitrato de miconazol - Sigma Pharma'),
	(397, 'Dalacin C - cloridrato de clindamicina - Hexal '),
	(398, 'Dalacin C - cloridrato de clindamicina - Ranbaxy'),
	(399, 'Dalacin C - fosfato de clindamicina - Eurofarma '),
	(400, 'Dalacin C - fosfato de clindamicina - Hipolabor'),
	(401, 'Dalacin C - fosfato de clindamicina - União Química'),
	(402, 'Daonil - glibenclamida - Apotex'),
	(403, 'Daonil - glibenclamida - Biosintética'),
	(404, 'Daonil - glibenclamida - EMS'),
	(405, 'Daonil - glibenclamida - Nature’s Plus'),
	(406, 'Daonil - glibenclamida - Ranbaxy'),
	(407, 'Daonil - glibenclamida - Sigma Pharma'),
	(408, 'Decadron - dexametasona - Cristália'),
	(409, 'Decadron - dexametasona - EMS'),
	(410, 'Decadron - dexametasona - Medley'),
	(411, 'Decadron - dexametasona - Neo Química'),
	(412, 'Decadron - dexametasona - Prati, Donaduzzi'),
	(413, 'Decadron - dexametasona - Sanval'),
	(414, 'Decadron - dexametasona - Teuto'),
	(415, 'Decadron - dexametasona - Sigma Pharma'),
	(416, 'Decadron - dexametasona - Nature ''s Plus'),
	(417, 'Decadron - dexametasona - EMS'),
	(418, 'Decadron - fosfato dissódico de dexametasona - Hypofarma'),
	(419, 'Decadron - fosfato dissódico de dexametasona - Teuto'),
	(420, 'Decadron - fosfato dissódico de dexametasona - EMS'),
	(421, 'Decadron - fosfato dissódico de dexametasona - Eurofarma '),
	(422, 'Depakene - valproato de sódio - Biolab Sanus'),
	(423, 'Depakene - valproato de sódio - EMS'),
	(424, 'Depakene - valproato de sódio - Nature ''s Plus'),
	(425, 'Depakene - valproato de sódio - Sigma Pharma'),
	(426, 'Dermazine - sulfadiazina de prata - Prati, Donaduzzi'),
	(427, 'Dermodex - nistatina + óxido de zinco - EMS'),
	(428, 'Dermodex - nistatina + óxido de zinco - Medley'),
	(429, 'Dermodex - nistatina + óxido de zinco - Nature´s Plus'),
	(430, 'Dermodex - nistatina + óxido de zinco - Sigma Pharma'),
	(431, 'Desonol - desonida - EMS'),
	(432, 'Desonol - desonida - Medley'),
	(433, 'Desonol - desonida - Sigma Pharma'),
	(434, 'Desonol - desonida - Medley'),
	(435, 'Desonol - desonida - EMS'),
	(436, 'Desonol - desonida - Nature''s Plus'),
	(437, 'Desonol - desonida - Medley'),
	(438, 'Desonol - desonida - Sigma Pharma'),
	(439, 'Diamicron - gliclazida - EMS'),
	(440, 'Digesan - bromoprida - Medley'),
	(441, 'Digesan - bromoprida - EMS'),
	(442, 'Digesan - bromoprida - Merck'),
	(443, 'Digesan - bromoprida - Prati, Donaduzzi'),
	(444, 'Digesan - bromoprida - Teuto'),
	(445, 'Digesan - bromoprida - Prati, Donaduzzi'),
	(446, 'Digesan - bromoprida - Medley'),
	(447, 'Digoxina - digoxina - Prati, Donaduzzi'),
	(448, 'Digoxina - digoxina - '),
	(449, 'Dilacoron - cloridrato de verapamil - Abbott '),
	(450, 'Dilacoron - cloridrato de verapamil - Hexal'),
	(451, 'Dilacoron - cloridrato de verapamil - Apotex'),
	(452, 'Dilacoron - cloridrato de verapamil - Nature’s Plus'),
	(453, 'Dilacoron - cloridrato de verapamil - Sigma Pharma'),
	(454, 'Dilacoron - cloridrato de verapamil - Teuto'),
	(455, 'Diprivan - propofol - Abbott'),
	(456, 'Diprogenta - dipropionato de betametasona + sulfato de gentamicina - Medley'),
	(457, 'Diprosalic - dipropionato de betametasona + ácido salicílico - EMS'),
	(458, 'Diprosalic - dipropionato de betametasona + ácido salicílico - Prati, Donaduzzi'),
	(459, 'Diprosalic - dipropionato de betametasona + ácido salicílico - Medley'),
	(460, 'Diprosalic - dipropionato de betametasona + ácido salicílico - Merck'),
	(461, 'Diprosalic - dipropionato de betametasona + ácido salicílico - Prati, Donaduzzi'),
	(462, 'Diprosone - dipropionato de betametasona - EMS'),
	(463, 'Diprosone - dipropionato de betametasona - Nature''s Plus'),
	(464, 'Diprosone - dipropionato de betametasona - Ranbaxy'),
	(465, 'Diprosone - dipropionato de betametasona - Sigma Pharma'),
	(466, 'Diprospan - dipropionato de betametasona + fosfato dissódico de betametasona - Eurofarma'),
	(467, 'Diprospan - dipropionato de betametasona + fosfato dissódico de betametasona - Brainfarma'),
	(468, 'Dobutrex - cloridrato de dobutamina - Abbott'),
	(469, 'Dobutrex - cloridrato de dobutamina - Eurofarma '),
	(470, 'Dormonid - midazolam - União Química'),
	(471, 'Dormonid - midazolam - Eurofarma'),
	(472, 'Dormonid - maleato de midazolam - Eurofarma'),
	(473, 'Dormonid - maleato de midazolam - Ranbaxy'),
	(474, 'Drenol - hidroclorotiazida - Neo Química'),
	(475, 'Elocom - furoato de mometasona - Eurofarma'),
	(476, 'Elocom - furoato de mometasona - '),
	(477, 'Eloxatin - oxaliplatina - Eurofarma'),
	(478, 'Epivir - lamivudina - Eurofarma'),
	(479, 'Epivir - lamivudina - Ranbaxy'),
	(480, 'Eulexin - flutamida - Asta Medica'),
	(481, 'Eulexin - flutamida - Hexal'),
	(482, 'Eulexin - flutamida - Apotex'),
	(483, 'Espasmo Luftal - Dimeticona + Metilbrometo de Homatropina - EMS'),
	(484, 'Feldene - piroxicam - EMS'),
	(485, 'Feldene - piroxicam - Merck'),
	(486, 'Feldene - piroxicam - Biosintética'),
	(487, 'Feldene - piroxicam - Nature ''s Plus'),
	(488, 'Feldene - piroxicam - Apotex'),
	(489, 'Feldene - piroxicam - Ranbaxy'),
	(490, 'Feldene - piroxicam - Hexal'),
	(491, 'Feldene - piroxicam - Ranbaxy'),
	(492, 'Feldene - piroxicam - Cinfa'),
	(493, 'Feldene - piroxicam - Ranbaxy'),
	(494, 'Feldene - piroxicam - Ativus'),
	(495, 'Flagyl - benzoilmetronidazol - EMS'),
	(496, 'Flagyl - benzoilmetronidazol - Neo Química'),
	(497, 'Flagyl - benzoilmetronidazol - Teuto'),
	(498, 'Flagyl - metronidazol - Hypofarma'),
	(499, 'Flagyl - metronidazol - Equiplex'),
	(500, 'Flagyl - metronidazol - Halex Istar'),
	(501, 'Flagyl - metronidazol - JP'),
	(502, 'Flagyl - metronidazol - Sanval'),
	(503, 'Flagyl - metronidazol - EMS'),
	(504, 'Flagyl - metronidazol - Prati, Donaduzzi'),
	(505, 'Flagyl - metronidazol - Teuto'),
	(506, 'Flagyl - metronidazol - Neo Química'),
	(507, 'Flagyl - metronidazol - EMS'),
	(508, 'Flagyl Nistatina - metronidazol + nistatina - Prati, Donaduzzi'),
	(509, 'Flanax - naproxeno sódico - Apotex'),
	(510, 'Flotac - diclofenaco colestiramina - Medley'),
	(511, 'Flotac - diclofenaco colestiramina - Novartis'),
	(512, 'Floxacin - norfloxacino - Apotex'),
	(513, 'Floxacin - norfloxacino - Biosintética'),
	(514, 'Floxacin - norfloxacino - Brainfarma'),
	(515, 'Floxacin - norfloxacino - EMS'),
	(516, 'Floxacin - norfloxacino - Medley'),
	(517, 'Floxacin - norfloxacino - Mepha'),
	(518, 'Floxacin - norfloxacino - Merck'),
	(519, 'Floxacin - norfloxacino - Nature´s Plus'),
	(520, 'Floxacin - norfloxacino - Novartis'),
	(521, 'Floxacin - norfloxacino - Ranbaxy'),
	(522, 'Floxstat - ofloxacino - Ranbaxy'),
	(523, 'Floxstat - ofloxacino - Teuto'),
	(524, 'Fluimucil - acetilcisteina - Eurofarma'),
	(525, 'Fluimucil - acetilcisteina - EMS'),
	(526, 'Fluimucil - acetilcisteina - Nature''s Plus'),
	(527, 'Fluimucil - acetilcisteina - Eurofarma'),
	(528, 'Fluimucil - acetilcisteina - EMS'),
	(529, 'Fluimucil - acetilcisteina - Eurofarma'),
	(530, 'Fluimucil - acetilcisteina - Nature´s Plus'),
	(531, 'Fluimucil - acetilcisteina - Prati, Donaduzzi'),
	(532, 'Fluimucil - acetilcisteina - Zambon'),
	(533, 'Fluoro-uracil - fluoruracila - Eurofarma'),
	(534, 'Fortaz - ceftazidima - AB Farmoquímica'),
	(535, 'Fortaz - ceftazidima - Eurofarma '),
	(536, 'Fosamax - alendronato sódico - Biosintética'),
	(537, 'Fosamax - alendronato sódico - Novartis'),
	(538, 'Frademicina - cloridrato de lincomicina - Neo Química'),
	(539, 'Frademicina - cloridrato de lincomicina - Teuto'),
	(540, 'Frademicina - cloridrato de lincomicina - EMS'),
	(541, 'Frontal - alprazolam - Apotex'),
	(542, 'Frontal - alprazolam - Arrow'),
	(543, 'Frontal - alprazolam - Eurofarma'),
	(544, 'Frontal - alprazolam - EMS'),
	(545, 'Frontal - alprazolam - Nature´s Plus'),
	(546, 'Frontal - alprazolam - Biosintética'),
	(547, 'Frontal - alprazolam - Novartis'),
	(548, 'Garamicina - sulfato de gentamicina - Cristália'),
	(549, 'Garamicina - sulfato de gentamicina - Ducto'),
	(550, 'Garamicina - sulfato de gentamicina - Prodotti'),
	(551, 'Garamicina - sulfato de gentamicina - Neo Química'),
	(552, 'Garamicina - sulfato de gentamicina - EMS'),
	(553, 'Gardenal - fenobarbital - União Química'),
	(554, 'Gemzar - cloridrato de gencitabina - Eurofarma'),
	(555, 'Gino-Canesten - clotrimazol - Medley'),
	(556, 'Gino-Canesten - clotrimazol - EMS'),
	(557, 'Glifage - cloridrato de metformina - EMS'),
	(558, 'Glifage - cloridrato de metformina - Medley'),
	(559, 'Glifage - cloridrato de metformina - Merck'),
	(560, 'Glifage - cloridrato de metformina - Nature´s Plus'),
	(561, 'Glifage - cloridrato de metformina - Sigma Pharma'),
	(562, 'Glifage - cloridrato de metformina - Biobrás'),
	(563, 'Glifage - cloridrato de metformina - Biosintética'),
	(564, 'Glifage - cloridrato de metformina - Brainfarma'),
	(565, 'Glifage - cloridrato de metformina - Bristol'),
	(566, 'Glifage - cloridrato de metformina - Ipca'),
	(567, 'Glifage - cloridrato de metformina - Mepha'),
	(568, 'Glifage - cloridrato de metformina - Ranbaxy'),
	(569, 'Gyno-Daktarin  - nitrato de miconazol - Medley'),
	(570, 'Gyno-Daktarin  - nitrato de miconazol - Nature''s Plus'),
	(571, 'Gyno-Daktarin  - nitrato de miconazol - Prati, Donaduzzi'),
	(572, 'Gyno-Daktarin  - nitrato de miconazol - Sigma Pharma'),
	(573, 'Gyno-Daktarin  - nitrato de miconazol - Teuto'),
	(574, 'Gyno-Icaden - nitrato de isoconazol - Ativus'),
	(575, 'Gyno-Icaden - nitrato de isoconazol - Medley'),
	(576, 'Gyno-Icaden - nitrato de isoconazol - Neo Química'),
	(577, 'Gyno-Icaden - nitrato de isoconazol - Prati, Donaduzzi'),
	(578, 'Gino-Pletil - tinidazol + nitrato de miconazol - Cristália'),
	(579, 'Gino-Pletil - tinidazol + nitrato de miconazol - Medley'),
	(580, 'Gino-Pletil - tinidazol + nitrato de miconazol - Nature ''s Plus'),
	(581, 'Gino-Pletil - tinidazol + nitrato de miconazol - Prati, Donaduzzi'),
	(582, 'Gino-Pletil - tinidazol + nitrato de miconazol - Sigma Pharma'),
	(583, 'Haldol - haloperidol - União Química'),
	(584, 'Haldol - haloperidol - Teuto'),
	(585, 'Helmiben - mebendazol + tiabendazol  - Prati, Donaduzzi'),
	(586, 'Helmiben - mebendazol + tiabendazol  - '),
	(587, 'Higroton - clortalidona - EMS'),
	(588, 'Higroton - clortalidona - Ranbaxy'),
	(589, 'Higroton - clortalidona - Nature´s Plus'),
	(590, 'Hypnomidate - etomidato - Cristália'),
	(591, 'Hytrin - cloridrato de terazosina - Abbott'),
	(592, 'Holoxane - ifosfamida - Eurofarma'),
	(593, 'Icaden - nitrato de isoconazol - EMS'),
	(594, 'Icaden - nitrato de isoconazol - Medley'),
	(595, 'Icaden - nitrato de isoconazol - Cristália'),
	(596, 'Imigran - succinato de sumatriptano - Novartis'),
	(597, 'Imovane - zopiclona - Apotex'),
	(598, 'Imovane - zopiclona - Arrow'),
	(599, 'Imovane - zopiclona - Nature´s Plus'),
	(600, 'Intal - cromoglicato dissódico - Apotex'),
	(601, 'Isordil - dinitrato de isossorbida - EMS'),
	(602, 'Isordil - dinitrato de isossorbida - Nature´s Plus'),
	(603, 'Isotrex - isotretinoína - Ranbaxy'),
	(604, 'Jumexil - cloridrato de selegilina - Apotex'),
	(605, 'Jumexil - cloridrato de selegilina - Biosintética'),
	(606, 'Kefazol - cefazolina sódica - Eurofarma '),
	(607, 'Kefazol - cefazolina sódica - Novafarma'),
	(608, 'Kefazol - cefazolina sódica - AB Farmoquímica'),
	(609, 'Keflex  - cefalexina  - Eurofarma '),
	(610, 'Keflex  - cefalexina  - EMS'),
	(611, 'Keflex  - cefalexina  - Medley'),
	(612, 'Keflex  - cefalexina  - Apotex'),
	(613, 'Keflex  - cefalexina  - AB Farmoquímica'),
	(614, 'Keflex  - cefalexina  - EMS'),
	(615, 'Keflex  - cefalexina  - Brainfarma'),
	(616, 'Keflex  - cefalexina  - Eurofarma '),
	(617, 'Keflex  - cefalexina  - Ranbaxy'),
	(618, 'Keflex  - cefalexina  - Mepha'),
	(619, 'Keflex  - cefalexina  - Novartis'),
	(620, 'Keflex  - cefalexina  - Teuto'),
	(621, 'Keflin neutro  - cefalotina sódica  - Teuto'),
	(622, 'Keflin neutro  - cefalotina sódica  - AB Farmoquímica'),
	(623, 'Keflin neutro  - cefalotina sódica  - EMS'),
	(624, 'Keflin neutro  - cefalotina sódica  - Eurofarma '),
	(625, 'Klaricid - claritromicina - EMS'),
	(626, 'Klaricid - claritromicina - Ranbaxy'),
	(627, 'Klaricid - claritromicina - Abbott'),
	(628, 'Klaricid - claritromicina - Novartis'),
	(629, 'Klaricid - claritromicina - Merck'),
	(630, 'Klaricid - claritromicina - Abbott'),
	(631, 'Klaricid - claritromicina - EMS'),
	(632, 'Klaricid - claritromicina - Mepha'),
	(633, 'Klaricid - claritromicina - Medley '),
	(634, 'Klaricid - claritromicina - Ranbaxy'),
	(635, 'Klaricid - claritromicina - Eurofarma'),
	(636, 'Kloren - cloreto de potássio - Prati, Donaduzzi'),
	(637, 'Kytril - cloridrato de granisetrona - Eurofarma'),
	(638, 'Lamictal - lamotrigina - Arrow'),
	(639, 'Lamisil - cloridrato de terbinafina - Eurofarma'),
	(640, 'Lamisil - cloridrato de terbinafina - Prati, Donaduzzi'),
	(641, 'Lamisil - cloridrato de terbinafina - EMS'),
	(642, 'Lamisil - cloridrato de terbinafina - Medley '),
	(643, 'Lamisil - cloridrato de terbinafina - Prati, Donaduzzi'),
	(644, 'Lamisil - cloridrato de terbinafina - Medley '),
	(645, 'Lamisil - cloridrato de terbinafina - EMS'),
	(646, 'Lamisil - cloridrato de terbinafina - Ranbaxy'),
	(647, 'Lamisil - cloridrato de terbinafina - Eurofarma'),
	(648, 'Lamisil - cloridrato de terbinafina - Apotex'),
	(649, 'Lanexat - flumazenil - Eurofarma'),
	(650, 'Lasix  - furosemida  - Halex Istar'),
	(651, 'Lasix  - furosemida  - Teuto'),
	(652, 'Lasix  - furosemida  - EMS'),
	(653, 'Lasix  - furosemida  - Hypofarma'),
	(654, 'Lasix  - furosemida  - Teuto'),
	(655, 'Lasix  - furosemida  - Biosintética'),
	(656, 'Lasix  - furosemida  - Cinfa'),
	(657, 'Leucovorin - folinato de cálcio - Asta Medica'),
	(658, 'Leucovorin - folinato de cálcio - Eurofarma'),
	(659, 'Leucovorin - folinato de cálcio - Asta Medica'),
	(660, 'Lexotan - bromazepam - Apotex'),
	(661, 'Lexotan - bromazepam - Abbott'),
	(662, 'Lexotan - bromazepam - Biosintética'),
	(663, 'Lexotan - bromazepam - EMS'),
	(664, 'Lexotan - bromazepam - Eurofarma'),
	(665, 'Lexotan - bromazepam - Medley'),
	(666, 'Lexotan - bromazepam - Nature ''s Plus'),
	(667, 'Lexotan - bromazepam - União Química'),
	(668, 'Lipidil - fenofibrato - Apotex'),
	(669, 'Lopid - genfibrozila - EMS'),
	(670, 'Lopid - genfibrozila - Medley'),
	(671, 'Lopid - genfibrozila - Nature ''s Plus'),
	(672, 'Lopid - genfibrozila - Sigma Pharma'),
	(673, 'Lopid - genfibrozila - Apotex'),
	(674, 'Lopid - genfibrozila - Biosintética'),
	(675, 'Lopressor - tartarato de metoprolol - Biosintética'),
	(676, 'Lopril D - captopril + hidroclorotiazida - Hexal'),
	(677, 'Lopril D - captopril + hidroclorotiazida - AB Farmoquímica'),
	(678, 'Lopril D - captopril + hidroclorotiazida - Novartis'),
	(679, 'Lopril D - captopril + hidroclorotiazida - Nature ''s Plus'),
	(680, 'Lopril D - captopril + hidroclorotiazida - EMS'),
	(681, 'Lopril D - captopril + hidroclorotiazida - Medley'),
	(682, 'Lopril D - captopril + hidroclorotiazida - Biosintética'),
	(683, 'Loprox - ciclopirox olamina - Prati, Donaduzzi'),
	(684, 'Lorax - lorazepam - Apotex'),
	(685, 'Lorax - lorazepam - Arrow'),
	(686, 'Lorax - lorazepam - EMS'),
	(687, 'Lorax - lorazepam - Medley'),
	(688, 'Lorax - lorazepam - Nature´s Plus'),
	(689, 'Lorax - lorazepam - Ranbaxy'),
	(690, 'Lorax - lorazepam - Sigma Pharma'),
	(691, 'Losec - omeprazol sódico - Cristália'),
	(692, 'Losec - omeprazol sódico - EMS'),
	(693, 'Losec - omeprazol sódico - Eurofarma '),
	(694, 'Lotensin - cloridrato de benazepril - Ranbaxy'),
	(695, 'Luftal - dimeticona  - EMS'),
	(696, 'Luftal - dimeticona  - Medley'),
	(697, 'Luftal - dimeticona  - Merck'),
	(698, 'Luftal - dimeticona  - Sigma Pharma'),
	(699, 'Luftal - dimeticona  - Abbott'),
	(700, 'Luftal - dimeticona  - EMS'),
	(701, 'Luftal - dimeticona  - Nature''s Plus'),
	(702, 'Luftal Max - dimeticona  - EMS'),
	(703, 'Luftal Max - dimeticona  - Medley'),
	(704, 'Luftal Max - dimeticona  - Nature ''s Plus'),
	(705, 'Luftal Max - dimeticona  - Sigma Pharma'),
	(706, 'Marcaina - cloridratode bupivacaina - Abbott'),
	(707, 'Maxcef - cloridrato de cefepima - AB Farmoquímica'),
	(708, 'Maxcef - cloridrato de cefepima - Eurofarma'),
	(709, 'Mefoxin  - cefoxitina sódica  - Eurofarma '),
	(710, 'Megestat - acetato de megestrol - Apotex'),
	(711, 'Megestat - acetato de megestrol - Asta Medica'),
	(712, 'Meronem IV - meropenem - Eurofarma'),
	(713, 'Meticorten - prednisona - Teuto'),
	(714, 'Meticorten - prednisona - Abbott'),
	(715, 'Meticorten - prednisona - EMS'),
	(716, 'Meticorten - prednisona - Eurofarma'),
	(717, 'Meticorten - prednisona - Nature''s Plus'),
	(718, 'Meticorten - prednisona - Sanval'),
	(719, 'Meticorten - prednisona - Sigma Pharma'),
	(720, 'Meticorten - prednisona - Brainfarma'),
	(721, 'Metrotex - metotrexato - Asta Medica'),
	(722, 'Mevacor - lovastatina - Brainfarma'),
	(723, 'Mevacor - lovastatina - Hexal'),
	(724, 'Mevacor - lovastatina - Mepha'),
	(725, 'Mevacor - lovastatina - Ranbaxy'),
	(726, 'Mevacor - lovastatina - Apotex'),
	(727, 'Mevacor - lovastatina - Novartis'),
	(728, 'Mevacor - lovastatina - Cinfa'),
	(729, 'Micostatin  - nistatina  - Cristália'),
	(730, 'Micostatin  - nistatina  - Ducto '),
	(731, 'Micostatin  - nistatina  - EMS'),
	(732, 'Micostatin  - nistatina  - Neo Química'),
	(733, 'Micostatin  - nistatina  - Prati, Donaduzzi'),
	(734, 'Micostatin  - nistatina  - Cristália'),
	(735, 'Micostatin  - nistatina  - Eurofarma '),
	(736, 'Micostatin  - nistatina  - Neo Química'),
	(737, 'Micostatin  - nistatina  - EMS'),
	(738, 'Micostatin  - nistatina  - Teuto'),
	(739, 'Micostatin  - nistatina  - Medley '),
	(740, 'Micostatin  - nistatina  - Prodotti'),
	(741, 'Micostatin  - nistatina  - Greenpharma'),
	(742, 'Micostatin  - nistatina  - Prati, Donaduzzi'),
	(743, 'Minomax - cloridrato de minociclina - Ranbaxy'),
	(744, 'Mitexan - mesna - Eurofarma'),
	(745, 'Moduretic - cloridrato de amilorida + hidroclorotiazida - Biosintética'),
	(746, 'Moduretic - cloridrato de amilorida + hidroclorotiazida - EMS'),
	(747, 'Moduretic - cloridrato de amilorida + hidroclorotiazida - Nature ''s Plus'),
	(748, 'Moduretic - cloridrato de amilorida + hidroclorotiazida - Sigma Pharma'),
	(749, 'Moduretic - cloridrato de amilorida + hidroclorotiazida - Ranbaxy'),
	(750, 'Monocordil - mononitrato de isossorbida - Eurofarma'),
	(751, 'Monopril - fosinopril sódico - Ranbaxy'),
	(752, 'Movatec - meloxicam - EMS'),
	(753, 'Movatec - meloxicam - Biosintética'),
	(754, 'Movatec - meloxicam - Eurofarma'),
	(755, 'Movatec - meloxicam - Medley'),
	(756, 'Movatec - meloxicam - Merck'),
	(757, 'Movatec - meloxicam - Nature''s Plus'),
	(758, 'Movatec - meloxicam - Sigma Pharma'),
	(759, 'Movatec - meloxicam - Zydus'),
	(760, 'Movatec - meloxicam - Eurofarma'),
	(761, 'Mucolitic - carbocisteína - Medley '),
	(762, 'Mucolitic - carbocisteína - Prati, Donaduzzi'),
	(763, 'Mucolitic - carbocisteína - EMS'),
	(764, 'Mucolitic - carbocisteína - Biosintética'),
	(765, 'Mucolitic - carbocisteína - Cifarma'),
	(766, 'Mucolitic - carbocisteína - Medley '),
	(767, 'Mucolitic - carbocisteína - Merck'),
	(768, 'Mucolitic - carbocisteína - Neo Química'),
	(769, 'Mucolitic - carbocisteína - Prati, Donaduzzi'),
	(770, 'Mucolitic - carbocisteína - Teuto'),
	(771, 'Mucosolvan - cloridrato de ambroxol - Cinfa'),
	(772, 'Mucosolvan - cloridrato de ambroxol - Abbott'),
	(773, 'Mucosolvan - cloridrato de ambroxol - Biosintética'),
	(774, 'Mucosolvan - cloridrato de ambroxol - Cristália'),
	(775, 'Mucosolvan - cloridrato de ambroxol - EMS'),
	(776, 'Mucosolvan - cloridrato de ambroxol - Medley'),
	(777, 'Mucosolvan - cloridrato de ambroxol - Neo Química'),
	(778, 'Mucosolvan - cloridrato de ambroxol - Prati, Donaduzzi'),
	(779, 'Mucosolvan - cloridrato de ambroxol - Teuto'),
	(780, 'Mucosolvan - cloridrato de ambroxol - Cristália'),
	(781, 'Mucosolvan - cloridrato de ambroxol - Abbott '),
	(782, 'Mucosolvan - cloridrato de ambroxol - Prati, Donaduzzi'),
	(783, 'Naprosyn - naproxeno - Apotex'),
	(784, 'Naprosyn - naproxeno - Biosintética'),
	(785, 'Naprosyn - naproxeno - Teuto'),
	(786, 'Natrilix - indapamida - Apotex'),
	(787, 'Nebacetin - sulfato de neomicina + bacitracina - Medley '),
	(788, 'Nebacetin - sulfato de neomicina + bacitracina - EMS'),
	(789, 'Neurontin - gabapentina - Apotex'),
	(790, 'Neurontin - gabapentina - Ranbaxy'),
	(791, 'Neurontin - gabapentina - Biosintética'),
	(792, 'Nimotop - nimodipino - Hexal'),
	(793, 'Nitrencord - nitrendipino - Biosintética'),
	(794, 'Nisulid - nimesulida - Eurofarma'),
	(795, 'Nisulid - nimesulida - Medley'),
	(796, 'Nisulid - nimesulida - Neo Química'),
	(797, 'Nisulid - nimesulida - EMS'),
	(798, 'Nisulid - nimesulida - EMS'),
	(799, 'Nisulid - nimesulida - Eurofarma'),
	(800, 'Nisulid - nimesulida - Medley'),
	(801, 'Nisulid - nimesulida - Novartis'),
	(802, 'Nizoral  - cetoconazol  - Medley'),
	(803, 'Nizoral  - cetoconazol  - Teuto'),
	(804, 'Nizoral  - cetoconazol  - EMS'),
	(805, 'Nizoral  - cetoconazol  - Neo Química'),
	(806, 'Nizoral  - cetoconazol  - Cristália'),
	(807, 'Nizoral  - cetoconazol  - Prati, Donaduzzi'),
	(808, 'Nizoral  - cetoconazol  - Cristália'),
	(809, 'Nizoral  - cetoconazol  - Medley'),
	(810, 'Nizoral  - cetoconazol  - EMS'),
	(811, 'Nizoral  - cetoconazol  - EMS'),
	(812, 'Nizoral  - cetoconazol  - Neo Química'),
	(813, 'Nizoral  - cetoconazol  - Ranbaxy'),
	(814, 'Nizoral  - cetoconazol  - Medley'),
	(815, 'Nizoral  - cetoconazol  - Apotex'),
	(816, 'Nizoral  - cetoconazol  - Mepha'),
	(817, 'Nizoral  - cetoconazol  - Teuto'),
	(818, 'Nolvadex - citrato de tamoxifeno - Hexal '),
	(819, 'Nootropil - piracetan - Hexal'),
	(820, 'Norvasc  - besilato de anlodipino - Teuto'),
	(821, 'Norvasc  - besilato de anlodipino - Biosintética'),
	(822, 'Norvasc  - besilato de anlodipino - Cristália'),
	(823, 'Norvasc  - besilato de anlodipino - Medley'),
	(824, 'Norvasc  - besilato de anlodipino - Brainfarma'),
	(825, 'Norvasc  - besilato de anlodipino - Merck'),
	(826, 'Norvasc  - besilato de anlodipino - Mepha'),
	(827, 'Norvasc  - besilato de anlodipino - Biolab Sanus'),
	(828, 'Norvasc  - besilato de anlodipino - Ranbaxy'),
	(829, 'Norvasc  - besilato de anlodipino - EMS'),
	(830, 'Norvasc  - besilato de anlodipino - Novartis'),
	(831, 'Novacort - cetoconazol + dipropionato de betametasona + sulfato de neomicina - Eurofarma'),
	(832, 'Novacort - cetoconazol + dipropionato de betametasona + sulfato de neomicina - Nature''s Plus'),
	(833, 'Novacort - cetoconazol + dipropionato de betametasona + sulfato de neomicina - Medley'),
	(834, 'Novacort - cetoconazol + dipropionato de betametasona + sulfato de neomicina - EMS'),
	(835, 'Novacort - cetoconazol + dipropionato de betametasona + sulfato de neomicina - Cristália'),
	(836, 'Novacort - cetoconazol + dipropionato de betametasona + sulfato de neomicina - Nature''s Plus'),
	(837, 'Novacort - cetoconazol + dipropionato de betametasona + sulfato de neomicina - Medley'),
	(838, 'Novacort - cetoconazol + dipropionato de betametasona + sulfato de neomicina - EMS'),
	(839, 'Novalgina - dipirona sódica - Greenpharma'),
	(840, 'Novalgina - dipirona sódica - Neo Química'),
	(841, 'Novalgina - dipirona sódica - Prati, Donaduzzi'),
	(842, 'Novalgina - dipirona sódica - EMS'),
	(843, 'Novalgina - dipirona sódica - Medley'),
	(844, 'Novalgina - dipirona sódica - EMS'),
	(845, 'Novalgina - dipirona sódica - Equiplex'),
	(846, 'Novalgina - dipirona sódica - Neo Química'),
	(847, 'Novalgina - dipirona sódica - Biosintética'),
	(848, 'Novalgina - dipirona sódica - Abbott'),
	(849, 'Novalgina - dipirona sódica - Ducto '),
	(850, 'Novalgina - dipirona sódica - Biosintética'),
	(851, 'Novalgina - dipirona sódica - EMS'),
	(852, 'Novalgina - dipirona sódica - Eurofarma'),
	(853, 'Novalgina - dipirona sódica - Greenpharma'),
	(854, 'Novalgina - dipirona sódica - Lafepe'),
	(855, 'Novalgina - dipirona sódica - Medley'),
	(856, 'Novalgina - dipirona sódica - Neo Química'),
	(857, 'Novalgina - dipirona sódica - Prati, Donaduzzi'),
	(858, 'Novalgina - dipirona sódica - Teuto'),
	(859, 'Novalgina - dipirona sódica - Theodoro F Sobral'),
	(860, 'Novamin  - sulfato de amicacina - Eurofarma '),
	(861, 'Novamin  - sulfato de amicacina - Teuto'),
	(862, 'Novamin  - sulfato de amicacina - EMS'),
	(863, 'Oceral - nitrato de oxiconazol - Prati, Donaduzzi'),
	(864, 'Oceral - nitrato de oxiconazol - '),
	(865, 'Oflox - ofloxacino - Alcon'),
	(866, 'Ogastro - lansoprazol - EMS'),
	(867, 'Ogastro - lansoprazol - Nature''s Plus'),
	(868, 'Ogastro - lansoprazol - Sigma Pharma'),
	(869, 'Ogastro - lansoprazol - Medley'),
	(870, 'Olcadil - cloxazolam - Eurofarma'),
	(871, 'Olcadil - cloxazolam - Novartis'),
	(872, 'Omcilon A M - acetonido de triancinolona + sulfato de neomicina + gramicidina + nistatina - Eurofarma'),
	(873, 'Omcilon A M - acetonido de triancinolona + sulfato de neomicina + gramicidina + nistatina - EMS'),
	(874, 'Omcilon A M - acetonido de triancinolona + sulfato de neomicina + gramicidina + nistatina - Eurofarma'),
	(875, 'Omcilon A M - acetonido de triancinolona + sulfato de neomicina + gramicidina + nistatina - EMS'),
	(876, 'Orelox - cefpodoxima proxetil - Ranbaxy'),
	(877, 'Orelox - cefpodoxima proxetil - '),
	(878, 'Otosynalar - acetonido de fluocinolona  + sulfato de neomicina + sulfato de polimixina b + cloridrato de lidocaia - EMS'),
	(879, 'Trileptal - oxcarbazepina - Novartis'),
	(880, 'Pamelor - cloridrato de nortriptilina - Eurofarma'),
	(881, 'Pantelmin - mebendazol - Abbott'),
	(882, 'Pantelmin - mebendazol - Cristália'),
	(883, 'Pantelmin - mebendazol - EMS'),
	(884, 'Pantelmin - mebendazol - Greenpharma'),
	(885, 'Pantelmin - mebendazol - Kinder'),
	(886, 'Pantelmin - mebendazol - Medley'),
	(887, 'Pantelmin - mebendazol - Neo Química'),
	(888, 'Pantelmin - mebendazol - Prati, Donaduzzi'),
	(889, 'Pantelmin - mebendazol - Teuto'),
	(890, 'Pantelmin - mebendazol - Kinder'),
	(891, 'Pantelmin - mebendazol - Neo Química'),
	(892, 'Pantelmin - mebendazol - Cristália'),
	(893, 'Pantelmin - mebendazol - EMS'),
	(894, 'Pantelmin - mebendazol - Prati, Donaduzzi'),
	(895, 'Pantelmin - mebendazol - Abbott '),
	(896, 'Pantelmin - mebendazol - Teuto'),
	(897, 'Pantozol - pantoprazol - EMS'),
	(898, 'Pantozol - pantoprazol - Nature''s Plus'),
	(899, 'Pantozol - pantoprazol - Medley'),
	(900, 'Pantozol - pantoprazol - Eurofarma'),
	(901, 'Pantozol - pantoprazol - Eurofarma'),
	(902, 'Pantozol - pantoprazol - Altana'),
	(903, 'Paraplatin - carboplatina - Eurofarma'),
	(904, 'Parlodel - mesilato de bromocriptina - Apotex'),
	(905, 'Penicilina G potássica - benzilpenicilina potássica - Eurofarma '),
	(906, 'Pen-Ve-Oral - fenoximetilpenicilina potássica - Eurofarma '),
	(907, 'Pen-Ve-Oral - fenoximetilpenicilina potássica - EMS'),
	(908, 'Pen-Ve-Oral - fenoximetilpenicilina potássica - Eurofarma '),
	(909, 'Peprazol - omeprazol - Mepha'),
	(910, 'Peprazol - omeprazol - Cinfa'),
	(911, 'Peprazol - omeprazol - Teuto'),
	(912, 'Peprazol - omeprazol - Medley '),
	(913, 'Peprazol - omeprazol - Libbs'),
	(914, 'Peprazol - omeprazol - EMS'),
	(915, 'Peprazol - omeprazol - Biosintética'),
	(916, 'Peprazol - omeprazol - Nature ''s Plus'),
	(917, 'Pepsamar - hidróxido de alumínio - Prati, Donaduzzi'),
	(918, 'Pepsamar - hidróxido de alumínio - EMS'),
	(919, 'Plasil  - cloridrato de metoclopramida - Teuto'),
	(920, 'Plasil  - cloridrato de metoclopramida - Medley'),
	(921, 'Plasil  - cloridrato de metoclopramida - Prati, Donaduzzi'),
	(922, 'Plasil  - cloridrato de metoclopramida - Neo Química'),
	(923, 'Plasil  - cloridrato de metoclopramida - Teuto'),
	(924, 'Plasil  - cloridrato de metoclopramida - EMS'),
	(925, 'Plasil  - cloridrato de metoclopramida - Halex Istar'),
	(926, 'Platiran - cisplatina - Asta Medica'),
	(927, 'Polaramine  - maleato de dexclorfeniramina - Brainfarma'),
	(928, 'Polaramine  - maleato de dexclorfeniramina - EMS'),
	(929, 'Polaramine  - maleato de dexclorfeniramina - Nature''s Plus'),
	(930, 'Polaramine  - maleato de dexclorfeniramina - Sigma Pharma'),
	(931, 'Polaramine  - maleato de dexclorfeniramina - Brainfarma'),
	(932, 'Polaramine  - maleato de dexclorfeniramina - Cristália'),
	(933, 'Polaramine  - maleato de dexclorfeniramina - EMS'),
	(934, 'Polaramine  - maleato de dexclorfeniramina - Medley'),
	(935, 'Polaramine  - maleato de dexclorfeniramina - Merck'),
	(936, 'Polaramine  - maleato de dexclorfeniramina - Neo Química'),
	(937, 'Polaramine  - maleato de dexclorfeniramina - Prati, Donaduzzi'),
	(938, 'Polaramine  - maleato de dexclorfeniramina - Teuto'),
	(939, 'Polaramine  - maleato de dexclorfeniramina - Brainfarma'),
	(940, 'Polaramine Expectorante - maleato de dexclorfeniramina + sulfato de pseudoefedrina + guaifenesina - Brainfarma'),
	(941, 'Polaramine Expectorante - maleato de dexclorfeniramina + sulfato de pseudoefedrina + guaifenesina - EMS'),
	(942, 'Polaramine Expectorante - maleato de dexclorfeniramina + sulfato de pseudoefedrina + guaifenesina - Medley'),
	(943, 'Polaramine Expectorante - maleato de dexclorfeniramina + sulfato de pseudoefedrina + guaifenesina - Nature´s Plus'),
	(944, 'Polaramine Expectorante - maleato de dexclorfeniramina + sulfato de pseudoefedrina + guaifenesina - Sigma Pharma'),
	(945, 'Pravacol - pravastatina sódica - Ranbaxy'),
	(946, 'Pravacol - pravastatina sódica - Apotex'),
	(947, 'Pravacol - pravastatina sódica - Arrow'),
	(948, 'Pred Fort - acetato prednisolona - Alcon'),
	(949, 'Prinzide - lisinopril + hidroclorotiazida - Biosintética'),
	(950, 'Prinzide - lisinopril + hidroclorotiazida - Merck'),
	(951, 'Prednisolon - fosfato sódico de prednisolona - Medley'),
	(952, 'Prednisolon - fosfato sódico de prednisolona - Prati, Donaduzzi'),
	(953, 'Proctyl - policresuleno + cloridrato de cinchocaína - Medley'),
	(954, 'Profenid e Profenid Retard - cetoprofeno - Medley'),
	(955, 'Profenid e Profenid Retard - cetoprofeno - Nature''s Plus'),
	(956, 'Profenid e Profenid Retard - cetoprofeno - EMS'),
	(957, 'Profenid e Profenid Retard - cetoprofeno - Medley'),
	(958, 'Profenid e Profenid Retard - cetoprofeno - Ranbaxy'),
	(959, 'Profenid e Profenid Retard - cetoprofeno - Apotex'),
	(960, 'Profenid e Profenid Retard - cetoprofeno - EMS'),
	(961, 'Profenid e Profenid Retard - cetoprofeno - Medley'),
	(962, 'Profenid e Profenid Retard - cetoprofeno - Medley'),
	(963, 'Profenid e Profenid Retard - cetoprofeno - EMS'),
	(964, 'Profenid e Profenid Retard - cetoprofeno - Cristália'),
	(965, 'Profenid e Profenid Retard - cetoprofeno - Eurofarma '),
	(966, 'Profenid e Profenid Retard - cetoprofeno - Eurofarma '),
	(967, 'Profenid e Profenid Retard - cetoprofeno - Cristália'),
	(968, 'Proflam - aceclofenaco - Ranbaxy'),
	(969, 'Propécia - finasterida - Biosintética'),
	(970, 'Propécia - finasterida - EMS'),
	(971, 'Propécia - finasterida - Eurofarma'),
	(972, 'Propécia - finasterida - Medley'),
	(973, 'Propécia - finasterida - Merck'),
	(974, 'Propécia - finasterida - Nature''s Plus'),
	(975, 'Propranolol - cloridrato de propranolol - Teuto'),
	(976, 'Propranolol - cloridrato de propranolol - União Química'),
	(977, 'Propranolol - cloridrato de propranolol - Neo Química'),
	(978, 'Propranolol - cloridrato de propranolol - EMS'),
	(979, 'Propranolol - cloridrato de propranolol - Nature''s Plus'),
	(980, 'Proscar - finasterida - EMS'),
	(981, 'Proscar - finasterida - Eurofarma'),
	(982, 'Proscar - finasterida - Medley'),
	(983, 'Proscar - finasterida - Merck'),
	(984, 'Proscar - finasterida - Nature ''s Plus'),
	(985, 'Prozac - cloridrato de fluoxetina - Apotex'),
	(986, 'Prozac - cloridrato de fluoxetina - Biosintética'),
	(987, 'Prozac - cloridrato de fluoxetina - EMS'),
	(988, 'Prozac - cloridrato de fluoxetina - Hexal '),
	(989, 'Prozac - cloridrato de fluoxetina - Mepha'),
	(990, 'Prozac - cloridrato de fluoxetina - Novartis'),
	(991, 'Prozac - cloridrato de fluoxetina - Ranbaxy'),
	(992, 'Prozac - cloridrato de fluoxetina - Sigma Pharma'),
	(993, 'Psorex - propionato de clobetasol - Ativus'),
	(994, 'Psorex - propionato de clobetasol - Eurofarma'),
	(995, 'Psorex - propionato de clobetasol - Medley'),
	(996, 'Psorex - propionato de clobetasol - Merck'),
	(997, 'Psorex - propionato de clobetasol - Neo Química'),
	(998, 'Psorex - propionato de clobetasol - Prati, Donaduzzi'),
	(999, 'Psorex - propionato de clobetasol - Ativus'),
	(1000, 'Psorex - propionato de clobetasol - Eurofarma'),
	(1001, 'Psorex - propionato de clobetasol - Medley'),
	(1002, 'Psorex - propionato de clobetasol - Merck'),
	(1003, 'Psorex - propionato de clobetasol - Neo Química'),
	(1004, 'Psorex - propionato de clobetasol - Medley '),
	(1005, 'Psorex - propionato de clobetasol - Merck'),
	(1006, 'Psorex - propionato de clobetasol - Eurofarma'),
	(1007, 'Quadriderm - valerato de betametasona + sulfato de gentamicina + clioquinol + tolnaftato - EMS'),
	(1008, 'Quadriderm - valerato de betametasona + sulfato de gentamicina + clioquinol + tolnaftato - Brainfarma'),
	(1009, 'Quadriderm - valerato de betametasona + sulfato de gentamicina + clioquinol + tolnaftato - EMS'),
	(1010, 'Quadriderm - valerato de betametasona + sulfato de gentamicina + clioquinol + tolnaftato - Brainfarma'),
	(1011, 'Remeron - mirtazapina - Novartis'),
	(1012, 'Renitec - maleato de enalapril - Biosintética'),
	(1013, 'Renitec - maleato de enalapril - Brainfarma'),
	(1014, 'Renitec - maleato de enalapril - Cristália'),
	(1015, 'Renitec - maleato de enalapril - EMS'),
	(1016, 'Renitec - maleato de enalapril - Hexal'),
	(1017, 'Renitec - maleato de enalapril - Medley'),
	(1018, 'Renitec - maleato de enalapril - Mepha'),
	(1019, 'Renitec - maleato de enalapril - Nature´s Plus '),
	(1020, 'Renitec - maleato de enalapril - Neo Química'),
	(1021, 'Renitec - maleato de enalapril - Ranbaxy'),
	(1022, 'Renitec - maleato de enalapril - Teuto'),
	(1023, 'Regaine - minoxidil - Apotex'),
	(1024, 'Revivan  - cloridrato de dopamina - Eurofarma '),
	(1025, 'Revivan  - cloridrato de dopamina - Teuto'),
	(1026, 'Revivan  - cloridrato de dopamina - União Química'),
	(1027, 'Rifocina Spray - rifamicina - EMS'),
	(1028, 'Rifocina Spray - rifamicina - Eurofarma'),
	(1029, 'Rifocina Spray - rifamicina - Nature''s Plus'),
	(1030, 'Rifocina Spray - rifamicina - Sigma Pharma'),
	(1031, 'Rino-Lastin - cloridrato de azelastina - EMS'),
	(1032, 'Risperdal - risperidona - Novartis'),
	(1033, 'Rivotril - clonazepam - Apotex'),
	(1034, 'Roacutan - isotretinoina - Ranbaxy'),
	(1035, 'Rocefin  - ceftriaxona sódica  - EMS'),
	(1036, 'Rocefin  - ceftriaxona sódica  - Eurofarma'),
	(1037, 'Rocefin  - ceftriaxona sódica  - AB Farmoquímica'),
	(1038, 'Rocefin  - ceftriaxona sódica  - Eurofarma '),
	(1039, 'Rocefin  - ceftriaxona sódica  - Neo Química'),
	(1040, 'Rocefin  - ceftriaxona sódica  - Novartis'),
	(1041, 'Rocefin  - ceftriaxona sódica  - Prodotti'),
	(1042, 'Rocefin  - ceftriaxona sódica  - Ranbaxy'),
	(1043, 'Rulid - roxitromicina - Novartis'),
	(1044, 'Sandimmun neoral - ciclosporina - Abbott'),
	(1045, 'Sandimmun neoral - ciclosporina - Nature´s Plus'),
	(1046, 'Sandimmun neoral - ciclosporina - Abbott'),
	(1047, 'Sandimmun neoral - ciclosporina - Nature´s Plus '),
	(1048, 'Secnidal - secnidazol - Mepha'),
	(1049, 'Secnidal - secnidazol - Neo Química'),
	(1050, 'Secnidal - secnidazol - Ranbaxy'),
	(1051, 'Secnidal - secnidazol - Medley'),
	(1052, 'Serzone - cloridrato de nefazodona - Ranbaxy'),
	(1053, 'Silomat - cloridrato de clobutinol - Medley'),
	(1054, 'Silomat - cloridrato de clobutinol - Prati, Donaduzzi'),
	(1055, 'Silomat - cloridrato de clobutinol - Medley'),
	(1056, 'Silomat - cloridrato de clobutinol - Prati, Donaduzzi'),
	(1057, 'Silomat Plus - cloridrato de clobutinol + succinato de doxilamina - União Química'),
	(1058, 'Silomat Plus - cloridrato de clobutinol + succinato de doxilamina - Medley'),
	(1059, 'Silomat Plus - cloridrato de clobutinol + succinato de doxilamina - Prati, Donaduzzi'),
	(1060, 'Silomat Plus - cloridrato de clobutinol + succinato de doxilamina - '),
	(1061, 'Silomat Plus - cloridrato de clobutinol + succinato de doxilamina - União Química'),
	(1062, 'Sinemet - carbidopa/levodopa - Biosintética'),
	(1063, 'Solu-cortef - succinato sódico de hidrocortisona - EMS'),
	(1064, 'Solu-cortef - succinato sódico de hidrocortisona - Eurofarma '),
	(1065, 'Sonebon - nitrazepam - Sigma Pharma'),
	(1066, 'Sonebon - nitrazepam - EMS'),
	(1067, 'Sonebon - nitrazepam - Nature ''s Plus'),
	(1068, 'Sorine - cloridrato de nafazolina - Medley'),
	(1069, 'Sotacor - cloridrato de sotalol - Merck'),
	(1070, 'Sotacor - cloridrato de sotalol - Ranbaxy'),
	(1071, 'Sotacor - cloridrato de sotalol - Hexal '),
	(1072, 'Sotacor - cloridrato de sotalol - Biosintética'),
	(1073, 'Splendil - felodipino - Hexal'),
	(1074, 'Sporanox - itraconazol - Brainfarma'),
	(1075, 'Sporanox - itraconazol - Mepha'),
	(1076, 'Sporanox - itraconazol - Ranbaxy'),
	(1077, 'Staficilin-N  - oxacilina sódica  - Eurofarma '),
	(1078, 'Staficilin-N  - oxacilina sódica  - Prodotti'),
	(1079, 'Staficilin-N  - oxacilina sódica  - Teuto'),
	(1080, 'Stilnox - tartarato de zolpidem - Hexal'),
	(1081, 'Stugeron - cinarizina - Mepha'),
	(1082, 'Stugeron - cinarizina - Ranbaxy'),
	(1083, 'Tagamet  - cimetidina - Hexal'),
	(1084, 'Tagamet  - cimetidina - Abbott'),
	(1085, 'Tagamet  - cimetidina - Neo Química'),
	(1086, 'Tagamet  - cimetidina - Teuto'),
	(1087, 'Tagamet  - cloridrato de cimetidina - Teuto'),
	(1088, 'Tagamet  - cloridrato de cimetidina - EMS'),
	(1089, 'Talsutin - cloridrato de tetraciclina + anfotericina b - Ativus'),
	(1090, 'Talsutin - cloridrato de tetraciclina + anfotericina b - Cristália'),
	(1091, 'Talsutin - cloridrato de tetraciclina + anfotericina b - EMS'),
	(1092, 'Talsutin - cloridrato de tetraciclina + anfotericina b - Medley '),
	(1093, 'Tavanic - levofloxacino - Ranbaxy'),
	(1094, 'Tavanic - levofloxacino - Brainfarma'),
	(1095, 'Tavanic - levofloxacino - Mepha'),
	(1096, 'Tavanic - levofloxacino - Eurofarma'),
	(1097, 'Taxol - paclitaxel - Eurofarma'),
	(1098, 'Taxotere - docetaxel - Eurofarma'),
	(1099, 'Tazocin - piperacilina sódica + tazobactam sódico - Eurofarma'),
	(1100, 'Tenoretic - atenolol + clortalidona - EMS'),
	(1101, 'Tenoretic - atenolol + clortalidona - Biosintética'),
	(1102, 'Tenoretic - atenolol + clortalidona - Nature''s Plus'),
	(1103, 'Tenoretic - atenolol + clortalidona - Merck'),
	(1104, 'Tegretol - carbamazepina - Biosintética'),
	(1105, 'Tegretol - carbamazepina - Eurofarma '),
	(1106, 'Tegretol - carbamazepina - EMS'),
	(1107, 'Tegretol - carbamazepina - Nature’s Plus'),
	(1108, 'Tegretol - carbamazepina - Abbott '),
	(1109, 'Ticlid - cloridrato de ticlopidina - Apotex'),
	(1110, 'Ticlid - cloridrato de ticlopidina - Cinfa'),
	(1111, 'Ticlid - cloridrato de ticlopidina - Biosintética'),
	(1112, 'Ticlid - cloridrato de ticlopidina - Merck'),
	(1113, 'Tilatil - tenoxicam - Ranbaxy'),
	(1114, 'Tilatil - tenoxicam - EMS'),
	(1115, 'Tilatil - tenoxicam - Nature’s Plus'),
	(1116, 'Tilatil - tenoxicam - Eurofarma '),
	(1117, 'Timoptol - maleato de timolol - Allergan'),
	(1118, 'Timoptol - maleato de timolol - Biosintética'),
	(1119, 'Timoptol - maleato de timolol - Alcon'),
	(1120, 'Timoptol - maleato de timolol - Apotex'),
	(1121, 'Timoptol - maleato de timolol - Cristália'),
	(1122, 'Timoptol - maleato de timolol - Genom'),
	(1123, 'Tobradex - tobramicina + dexametaxona - Allergan'),
	(1124, 'Tobradex - tobramicina + dexametaxona - Alcon'),
	(1125, 'Tobrex - tobramicina - Alcon'),
	(1126, 'Tobrex - tobramicina - Biosintética'),
	(1127, 'Tobrex - tobramicina - Cristália'),
	(1128, 'Tramal - cloridrato de tramadol - Hexal'),
	(1129, 'Tramal - cloridrato de tramadol - Mepha'),
	(1130, 'Tramal - cloridrato de tramadol - Nature''s Plus'),
	(1131, 'Tramal - cloridrato de tramadol - Sigma Pharma'),
	(1132, 'Tramal - cloridrato de tramadol - Eurofarma '),
	(1133, 'Tramal - cloridrato de tramadol - Mepha'),
	(1134, 'Tramal - cloridrato de tramadol - União Química'),
	(1135, 'Tramal Retard - cloridrato de tramadol - EMS'),
	(1136, 'Tracrium - besilato de atracurio - Abbott'),
	(1137, 'Tralen - tioconazol - EMS'),
	(1138, 'Tralen - tioconazol - Eurofarma'),
	(1139, 'Tralen - tioconazol - Medley '),
	(1140, 'Tralen - tioconazol - Prati, Donaduzzi'),
	(1141, 'Tralen - tioconazol - EMS'),
	(1142, 'Tralen - tioconazol - Medley '),
	(1143, 'Tralen - tioconazol - Prati, Donaduzzi'),
	(1144, 'Tralen - tioconazol - EMS'),
	(1145, 'Trental - pentoxifilina - Apotex'),
	(1146, 'Trental - pentoxifilina - Biosintética'),
	(1147, 'Trental - pentoxifilina - EMS'),
	(1148, 'Trental - pentoxifilina - Nature ''s Plus'),
	(1149, 'Trental Vert - pentoxifilina - Nature''s Plus'),
	(1150, 'Trental Vert - pentoxifilina - Hexal'),
	(1151, 'Trental Vert - pentoxifilina - EMS'),
	(1152, 'Triatec - ramipril - Biosintética'),
	(1153, 'Triatec - ramipril - Brainfarma'),
	(1154, 'Triatec - ramipril - Mepha'),
	(1155, 'Triatec - ramipril - Novartis'),
	(1156, 'Triatec - ramipril - Ranbaxy'),
	(1157, 'Trusopt - cloridrato de dorzolamida - Biosintética'),
	(1158, 'Tryptanol - cloridrato de amitriptilina - Ranbaxy'),
	(1159, 'Tryptanol - cloridrato de amitriptilina - Eurofarma'),
	(1160, 'Tryptanol - cloridrato de amitriptilina - Mepha'),
	(1161, 'Tryptanol - cloridrato de amitriptilina - Neo Química'),
	(1162, 'Tussiflex D - dropropizina - Medley'),
	(1163, 'Tussiflex D - dropropizina - Neo Química'),
	(1164, 'Tussiflex D - dropropizina - Prati, Donaduzzi'),
	(1165, 'Tussiflex D - dropropizina - União Química'),
	(1166, 'Tussiflex D - dropropizina - Prati, Donaduzzi'),
	(1167, 'Tylenol - paracetamol  - EMS'),
	(1168, 'Tylenol - paracetamol  - Biosintética'),
	(1169, 'Tylenol - paracetamol  - Eurofarma'),
	(1170, 'Tylenol - paracetamol  - Greenpharma'),
	(1171, 'Tylenol - paracetamol  - Hipolabor'),
	(1172, 'Tylenol - paracetamol  - Medley '),
	(1173, 'Tylenol - paracetamol  - Merck'),
	(1174, 'Tylenol - paracetamol  - Neo Química'),
	(1175, 'Tylenol - paracetamol  - Prati, Donaduzzi'),
	(1176, 'Tylenol - paracetamol  - Prodotti'),
	(1177, 'Tylenol - paracetamol  - Teuto'),
	(1178, 'Tylenol - paracetamol  - Theodoro F Sobral'),
	(1179, 'Tylenol - paracetamol  - União Química'),
	(1180, 'Tylenol - paracetamol  - Greenpharma'),
	(1181, 'Tylenol - paracetamol  - Kinder'),
	(1182, 'Tylenol - paracetamol  - Brainfarma'),
	(1183, 'Tylenol - paracetamol  - Bunker'),
	(1184, 'Tylenol - paracetamol  - Eurofarma'),
	(1185, 'Tylenol - paracetamol  - Neo Química'),
	(1186, 'Tylenol - paracetamol  - Prati, Donaduzzi'),
	(1187, 'Tylenol - paracetamol  - União Química'),
	(1188, 'Tylenol - paracetamol  - EMS'),
	(1189, 'Tylenol - paracetamol  - Medley '),
	(1190, 'Tylenol - paracetamol  - Merck'),
	(1191, 'Tylenol - paracetamol  - Prati, Donaduzzi'),
	(1192, 'Tylenol - paracetamol  - Apotex'),
	(1193, 'Tylenol - paracetamol  - Neo Química'),
	(1194, 'Tylenol - paracetamol  - Hipolabor'),
	(1195, 'Tylenol - paracetamol  - Teuto'),
	(1196, 'Unasyn - sulbactam sódica + ampicilina sódica - Eurofarma'),
	(1197, 'Valium  - diazepam  - Nature´s Plus '),
	(1198, 'Valium  - diazepam  - União Química'),
	(1199, 'Valium  - diazepam  - EMS'),
	(1200, 'Valium  - diazepam  - Ranbaxy'),
	(1201, 'Vancocina  - cloridrato de vancomicina - Eurofarma '),
	(1202, 'Vibramicina - cloridrato de doxicilina - Apotex'),
	(1203, 'Vibramicina - cloridrato de doxicilina - EMS'),
	(1204, 'Vibramicina - cloridrato de doxicilina - Nature''s Plus'),
	(1205, 'Vibramicina - cloridrato de doxicilina - Ranbaxy'),
	(1206, 'Vibramicina - cloridrato de doxicilina - Sigma Pharma'),
	(1207, 'Vibramicina - doxicilina - Hexal'),
	(1208, 'Viofórmio-Hidrocortisona - clioquinol + hidrocortisona - EMS'),
	(1209, 'Viramune - nevirapina - AB Farmoquímica'),
	(1210, 'Viramune - nevirapina - Eurofarma'),
	(1211, 'Viramune - nevirapina - Ranbaxy'),
	(1212, 'Voltaren - diclofenaco sódico - EMS'),
	(1213, 'Voltaren - diclofenaco sódico - Ducto '),
	(1214, 'Voltaren - diclofenaco sódico - Eurofarma '),
	(1215, 'Voltaren - diclofenaco sódico - Hypofarma'),
	(1216, 'Voltaren - diclofenaco sódico - Medley '),
	(1217, 'Voltaren - diclofenaco sódico - Neo Química'),
	(1218, 'Voltaren - diclofenaco sódico - Prodotti'),
	(1219, 'Voltaren - diclofenaco sódico - Teuto'),
	(1220, 'Voltaren - diclofenaco sódico - União Química'),
	(1221, 'Voltaren - diclofenaco sódico - EMS'),
	(1222, 'Voltaren - diclofenaco sódico - Biosintética'),
	(1223, 'Voltaren - diclofenaco sódico - Brainfarma'),
	(1224, 'Voltaren - diclofenaco sódico - Cinfa'),
	(1225, 'Voltaren - diclofenaco sódico - Hexal'),
	(1226, 'Voltaren - diclofenaco sódico - Knoll'),
	(1227, 'Voltaren - diclofenaco sódico - Medley '),
	(1228, 'Voltaren - diclofenaco sódico - Mepha'),
	(1229, 'Voltaren - diclofenaco sódico - Novartis'),
	(1230, 'Voltaren - diclofenaco sódico - Ranbaxy'),
	(1231, 'Voltaren Retard - diclofenaco sódico - EMS'),
	(1232, 'Voltaren Retard - diclofenaco sódico - Ranbaxy'),
	(1233, 'Xarope Vick - guaifenesina - EMS'),
	(1234, 'Xarope Vick - guaifenesina - Nature''s Plus'),
	(1235, 'Xarope Vick - guaifenesina - Sigma Pharma'),
	(1236, 'Xylocaína - cloridrato de lidocaína - Cristália'),
	(1237, 'Xylocaína - cloridrato de lidocaína - Hipolabor'),
	(1238, 'Xylocaína - cloridrato de lidocaína - Abbott '),
	(1239, 'Xylocaína - cloridrato de lidocaína - Hipolabor'),
	(1240, 'Xylocaína - cloridrato de lidocaína - Hypofarma'),
	(1241, 'Xylocaína com Epinefrina - cloridrato de lidocaína + epinefrina - Abbott'),
	(1242, 'Xylocaína Pesada 5% - cloridrato de lidocaína + glicose - Abbott'),
	(1243, 'Zaditen - fumarato de cetotifeno - Apotex'),
	(1244, 'Zaditen - fumarato de cetotifeno - Ativus'),
	(1245, 'Zaditen - fumarato de cetotifeno - Medley '),
	(1246, 'Zaditen - fumarato de cetotifeno - Meeck'),
	(1247, 'Zaditen - fumarato de cetotifeno - Nature ''s Plus'),
	(1248, 'Zaditen - fumarato de cetotifeno - Sigma Pharma'),
	(1249, 'Zaditen - fumarato de cetotifeno - União Química'),
	(1250, 'Zaditen - fumarato de cetotifeno - Ativus'),
	(1251, 'Zaditen - fumarato de cetotifeno - EMS'),
	(1252, 'Zaditen - fumarato de cetotifeno - Medley '),
	(1253, 'Zaditen - fumarato de cetotifeno - Nature''s Plus'),
	(1254, 'Zaditen - fumarato de cetotifeno - Sigma Pharma'),
	(1255, 'Zaditen - fumarato de cetotifeno - EMS'),
	(1256, 'Zentel - albendazol - Ducto '),
	(1257, 'Zentel - albendazol - EMS'),
	(1258, 'Zentel - albendazol - Greenpharma'),
	(1259, 'Zentel - albendazol - Neo Química'),
	(1260, 'Zentel - albendazol - Prati, Donaduzzi'),
	(1261, 'Zentel - albendazol - Teuto'),
	(1262, 'Zentel - albendazol - Abbott'),
	(1263, 'Zentel - albendazol - EMS'),
	(1264, 'Zentel - albendazol - Nature''s Plus'),
	(1265, 'Zentel - albendazol - Neo Química'),
	(1266, 'Zentel - albendazol - Prati, Donaduzzi'),
	(1267, 'Zentel - albendazol - Sigma Pharma'),
	(1268, 'Zeritavir - estavudina - Ranbaxy'),
	(1269, 'Zeritavir - estavudina - AB Farmoquímica'),
	(1270, 'Zestril - lisinopril - Biosintética'),
	(1271, 'Zestril - lisinopril - Cinfa'),
	(1272, 'Zestril - lisinopril - Brainfarma'),
	(1273, 'Zestril - lisinopril - Cristália'),
	(1274, 'Zestril - lisinopril - Hexal'),
	(1275, 'Zestril - lisinopril - Ipca'),
	(1276, 'Zestril - lisinopril - Medley'),
	(1277, 'Zestril - lisinopril - Mepha'),
	(1278, 'Zestril - lisinopril - Merck'),
	(1279, 'Zestril - lisinopril - Novartis'),
	(1280, 'Zestril - lisinopril - Ranbaxy'),
	(1281, 'Zestril - lisinopril - Teuto'),
	(1282, 'Zestril - lisinopril - EMS'),
	(1283, 'Zestril - lisinopril - Nature´s Plus '),
	(1284, 'Zestril - lisinopril - Sigma Pharma'),
	(1285, 'Zinacef - cefuroxima sódica - AB Farmoquímica'),
	(1286, 'Zinacef - cefuroxima sódica - Eurofarma'),
	(1287, 'Zinacef - cefuroxima sódica - Novartis'),
	(1288, 'Zinnat - axetil cefuroxima - Ranbaxy'),
	(1289, 'Zinnat - axetil cefuroxima - Mepha'),
	(1290, 'Zinnat - axetil cefuroxima - Ranbaxy'),
	(1291, 'Zitromax - azitromicina - EMS'),
	(1292, 'Zitromax - azitromicina - Eurofarma'),
	(1293, 'Zitromax - azitromicina - Mepha'),
	(1294, 'Zitromax - azitromicina - Novartis'),
	(1295, 'Zitromax - azitromicina - Ranbaxy'),
	(1296, 'Zitromax - azitromicina - EMS'),
	(1297, 'Zitromax - azitromicina - Ranbaxy'),
	(1298, 'Zocor - sinvastatina - EMS'),
	(1299, 'Zocor - sinvastatina - Ranbaxy'),
	(1300, 'Zocor - sinvastatina - Brainfarma'),
	(1301, 'Zocor - sinvastatina - Mepha'),
	(1302, 'Zocor - sinvastatina - Medley'),
	(1303, 'Zocor - sinvastatina - Arrow'),
	(1304, 'Zocor - sinvastatina - Hexal'),
	(1305, 'Zocor - sinvastatina - Novartis'),
	(1306, 'Zofran - cloridrato de ondansetrona - Eurofarma'),
	(1307, 'Zofran - cloridrato de ondansetrona - Ipca'),
	(1308, 'Zofran - cloridrato de ondansetrona - Bristol'),
	(1309, 'Zoloft - cloridrato de sertralina - Biosintética'),
	(1310, 'Zoloft - cloridrato de sertralina - Brainfarma'),
	(1311, 'Zoloft - cloridrato de sertralina - Eurofarma '),
	(1312, 'Zoloft - cloridrato de sertralina - Medley'),
	(1313, 'Zoloft - cloridrato de sertralina - Mepha'),
	(1314, 'Zoloft - cloridrato de sertralina - Novartis'),
	(1315, 'Zoloft - cloridrato de sertralina - Ranbaxy'),
	(1316, 'Zoltec - fluconazol - Teuto'),
	(1317, 'Zoltec - fluconazol - Medley'),
	(1318, 'Zoltec - fluconazol - Nature´s Plus '),
	(1319, 'Zoltec - fluconazol - EMS'),
	(1320, 'Zoltec - fluconazol - Ranbaxy'),
	(1321, 'Zoltec - fluconazol - Eurofarma'),
	(1322, 'Zoltec - fluconazol - Halex Istar'),
	(1323, 'Zovirax - fluconazol - Apotex'),
	(1324, 'Zovirax - fluconazol - Mepha'),
	(1325, 'Zovirax - fluconazol - Neo Química'),
	(1326, 'Zovirax - fluconazol - Merck'),
	(1327, 'Zovirax - fluconazol - Hexal'),
	(1328, 'Zovirax - fluconazol - Ranbaxy'),
	(1329, 'Zovirax - fluconazol - Eurofarma '),
	(1330, 'Zovirax - fluconazol - Abbott'),
	(1331, 'Zovirax - fluconazol - Cristália'),
	(1332, 'Zovirax - fluconazol - EMS'),
	(1333, 'Zovirax - fluconazol - Medley'),
	(1334, 'Zovirax - fluconazol - Neo Química'),
	(1335, 'Zovirax - fluconazol - Prati, Donaduzzi'),
	(1336, 'Zovirax - fluconazol - Ranbaxy'),
	(1337, 'Zovirax - fluconazol - Teuto'),
	(1338, 'Zyloric - alopurinol - Hexal'),
	(1339, 'Zyloric - alopurinol - Apotex'),
	(1340, 'Zyrtec - dicloridrato de cetirizina - Medley'),
	(1341, 'Zyrtec - dicloridrato de cetirizina - Prati, Donaduzzi'),
	(1342, 'Zyrtec - dicloridrato de cetirizina - Bristol'),
	(1343, 'Zyrtec - dicloridrato de cetirizina - Biosintética'),
	(1344, 'Zyrtec - dicloridrato de cetirizina - Hexal'),
	(1345, 'Zyrtec - dicloridrato de cetirizina - Ipca'),
	(1346, 'Zyrtec - dicloridrato de cetirizina - Medley'),
	(1347, 'Zyrtec - dicloridrato de cetirizina - ');